AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'hoginsbuapim'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'apim-demo-deployment'
VM_USERNAME: 'hginsburg'
ACCOUNT_NAME: 'github.com/howardginsburg'
CICD_AGENT_TYPE: 'github'
CERT_TYPE: 'selfsigned'